Transfer a file to your server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,29 +1,26 @@
 #!/usr/bin/env bash
-#check command-line parameters
-
+# checking for command line arguments
 if [ $# -lt 4 ]
 then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-#assign arguments to vars
+# assigning paramentals to variables
 
-file_path=$f
-ip=$i
-username=$u
-ssh_key_path=$s
-
-#disable strict host key checking
-
-scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$ip:~/"
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
 
 
-#checking if file transfer success?
+# disabbling strict host key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
+# checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-	echo "File Transfer Success"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "File Transfer Failed"
+  echo "FILE TRANSFER FAILED"
 fi
