transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,26 +1,29 @@
 #!/usr/bin/env bash
-# checking for command line arguments
+#check command-line parameters
+
 if [ $# -lt 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
 
-# assigning paramentals to variables
+#assign arguments to vars
 
-path_to_file=$1
-ip=$2
-username=$3
-path_to_ssh_key=$4
+file_path=$f
+ip=$i
+username=$u
+ssh_key_path=$s
+
+#disable strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$ip:~/"
 
 
-# disabbling strict host key checking
-scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+#checking if file transfer success?
 
-# checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-  echo "FILE TRANSFER WAS SUCCESSFULL"
+	echo "File Transfer Success"
 else
-  echo "FILE TRANSFER FAILED"
+	echo "File Transfer Failed"
 fi
